# Generated by Django 3.0.8 on 2020-07-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200717_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='decription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
